// <auto-generated />
using System;
using ChronoVoid.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChronoVoid.API.Migrations
{
    [DbContext(typeof(ChronoVoidContext))]
    [Migration("20250803031328_AddUserPasswordAndNodeDetails")]
    partial class AddUserPasswordAndNodeDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChronoVoid.API.Models.HyperTunnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("ToNodeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToNodeId");

                    b.HasIndex("FromNodeId", "ToNodeId")
                        .IsUnique();

                    b.ToTable("HyperTunnels");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.NeuralNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasQuantumStation")
                        .HasColumnType("boolean");

                    b.Property<int>("NodeNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PlanetCount")
                        .HasColumnType("integer");

                    b.Property<int>("RealmId")
                        .HasColumnType("integer");

                    b.Property<string>("StarName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RealmId", "NodeNumber")
                        .IsUnique();

                    b.ToTable("NeuralNodes");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.NexusRealm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NoDeadNodes")
                        .HasColumnType("boolean");

                    b.Property<int>("NodeCount")
                        .HasColumnType("integer");

                    b.Property<int>("QuantumStationSeedRate")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NexusRealms");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoHolds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RealmId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentNodeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RealmId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.HyperTunnel", b =>
                {
                    b.HasOne("ChronoVoid.API.Models.NeuralNode", "FromNode")
                        .WithMany("OutgoingTunnels")
                        .HasForeignKey("FromNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoVoid.API.Models.NeuralNode", "ToNode")
                        .WithMany("IncomingTunnels")
                        .HasForeignKey("ToNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.NeuralNode", b =>
                {
                    b.HasOne("ChronoVoid.API.Models.NexusRealm", "Realm")
                        .WithMany("Nodes")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.User", b =>
                {
                    b.HasOne("ChronoVoid.API.Models.NeuralNode", "CurrentNode")
                        .WithMany("CurrentUsers")
                        .HasForeignKey("CurrentNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChronoVoid.API.Models.NexusRealm", "Realm")
                        .WithMany("Users")
                        .HasForeignKey("RealmId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentNode");

                    b.Navigation("Realm");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.NeuralNode", b =>
                {
                    b.Navigation("CurrentUsers");

                    b.Navigation("IncomingTunnels");

                    b.Navigation("OutgoingTunnels");
                });

            modelBuilder.Entity("ChronoVoid.API.Models.NexusRealm", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
